

"""

Amaç: LSTM tabanlı dil modeli ile metin üretimi (text generation). eğitimi verisi için gemini ile türkçe günlük cümleler oluştur. model verilen başlangıç kelimesinden yeni kelimeler ya da cümleler generate edecek
Adımlar:
    - eğitim verisini gemini ile üret (günlük cümleler)
    - tokenization ile kelimeleri sayısal vektörlere çevir
    - n-gram dizeleri oluştur -> dil modeli için girdi ve çıktı çiftleri hazırlama
    - padding ile tüm dizileri aynı uzunluğa getir
    - LSTM tabanlı modeli kur
    - modeli compile ve fit et
    - yeni metin üretimi için custom function yaz

pip install tensorflow, keras, numpy
"""

import numpy as np
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Model
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Dense, LSTM, Input, Embedding


texts = [
    "Bugün hava çok güzel, dışarıda yürüyüş yapmayı düşünüyorum.",
    "Kitap okumak beni gerçekten mutlu ediyor.",
    "Sabah kahvesi içmeden güne başlayamıyorum.",
    "Yarınki toplantı için hazırlık yapmam gerekiyor.",
    "En sevdiğim dizi yeni sezonuna başladı.",
    "Akşam yemeğinde ne pişireceğime henüz karar vermedim.",
    "Market alışverişi listesini mutfak masasına bıraktım.",
    "Telefonumun şarjı bitmek üzere, şarj aletini bulmam lazım.",
    "Hafta sonu arkadaşlarla pikniğe gitmek için sözleştik.",
    "Bugün iş yerinde oldukça yoğun bir gün geçirdim.",
    "Yeni aldığım kulaklığın ses kalitesi gerçekten harika.",
    "Evi biraz toparlasam iyi olacak, her yer birbirine girmiş.",
    "Kışlık kıyafetleri dolabın üst rafına kaldırdım.",
    "Yolda gelirken çok sevdiğim eski bir şarkıya rastladım.",
    "Bu hafta sonu biraz dinlenmek ve uyumak istiyorum.",
    "Okula giderken otobüsü kaçırmamak için acele etmeliyim.",
    "Bitki yetiştirmek insana gerçekten huzur veriyor.",
    "Yeni bir dil öğrenmek için her gün pratik yapıyorum.",
    "Bu akşam sinemaya gitmek için bilet aldım.",
    "Spor yapmak kendimi daha enerjik hissetmemi sağlıyor.",
    "Bilgisayarımın ekranı aniden karardı, umarım bozulmamıştır.",
    "Tatil planları yapmak bile beni heyecanlandırmaya yetiyor.",
    "Akşam serinliğinde balkonda oturmak çok keyifli.",
    "Çocukken en çok saklambaç oynamayı severdim.",
    "Bugün kendime yeni bir spor ayakkabı aldım.",
    "Yemekten sonra çay içmek bizim evin olmazsa olmazıdır.",
    "Kütüphaneye gidip sessizce çalışmak bana iyi geliyor.",
    "En kısa zamanda diş randevusu almam gerekiyor.",
    "Yaz mevsiminin gelmesini dört gözle bekliyorum.",
    "Fotoğraf çekmek için harika bir manzara yakaladım.",
    "Bugün metro her zamankinden daha kalabalıktı.",
    "Yağmurlu havalarda pencere kenarında oturmayı severim.",
    "Komşumuzun köpeği bahçede oyun oynamaya bayılıyor.",
    "Yarın sabah erkenden kalkıp yürüyüşe çıkacağım.",
    "Dolaptaki meyvelerin tazeliği gitmeden tüketmeliyiz.",
    "En sevdiğim yazarın yeni kitabı ön siparişe çıkmış.",
    "Arabanın bakım zamanı geldi, servise götürmem lazım.",
    "Mutfak musluğu sızdırıyor, bir usta çağırmalıyız.",
    "Bugün öğle yemeğini dışarıda yemeye karar verdik.",
    "Eski fotoğraflara bakmak beni geçmişe götürdü.",
    "Ders çalışırken müzik dinlemek odaklanmamı zorlaştırıyor.",
    "Haftalık temizlik yapmak için pazar gününü ayırdım.",
    "Güneş gözlüğümü nerede bıraktığımı bir türlü hatırlayamıyorum.",
    "Pazardan taze sebze ve meyve almak çok daha ekonomik.",
    "Akşam yatmadan önce biraz yoga yapmak beni rahatlatıyor.",
    "İnternet bağlantısında bir sorun var gibi görünüyor.",
    "Arkadaşımın doğum günü için hediye seçmekte zorlanıyorum.",
    "Şehir dışındaki akrabalarımızı ziyaret etmeyi planlıyoruz.",
    "Gitar çalmayı öğrenmek her zaman hayalimdi.",
    "Bugün trafikte çok fazla vakit kaybettim.",
    "Yeni tarifler denemek mutfaktaki hobim haline geldi.",
    "Sınav sonuçlarının açıklanmasını heyecanla bekliyorum.",
    "Hava kararmadan eve dönmüş olmayı umuyorum.",
    "Okuduğum bu makale ufkumu gerçekten açtı.",
    "Sabah uyandığımda kuş seslerini duymak çok huzurlu.",
    "Kışın sıcak çikolata içmek en büyük keyfim.",
    "Odamın duvarlarını farklı bir renge boyatmak istiyorum.",
    "Bu ay bütçemi biraz daha dikkatli kullanmalıyım.",
    "Kedim koltuğun üzerinde mışıl mışıl uyuyor.",
    "İş arkadaşlarımla öğle arasında kısa bir yürüyüş yaptık.",
    "Televizyondaki tartışma programı ilgimi çekmedi.",
    "Ayakkabılarımı kapının önünde bırakmamam konusunda uyarıldım.",
    "Bugün kendimi çok daha üretken hissediyorum.",
    "Kuzenimin düğünü için şık bir elbise bakıyorum.",
    "Piyano resitaline gitmek için sabırsızlanıyorum.",
    "Deniz kenarında oturup dalgaları izlemek çok rahatlatıcı.",
    "Saçlarımı biraz kestirsem mi diye düşünüyorum.",
    "Yarın hava durumuna göre şemsiyemi yanıma alacağım.",
    "Bu akşam erken uyuyup uykumu almalıyım.",
    "Okulun kütüphanesi sınav haftasında çok kalabalık oluyor.",
    "Yeni bir diziye başladım, sürükleyici bir konusu var.",
    "Eski arkadaşlarımla buluşmak bana çok iyi geldi.",
    "Bilgisayar oyunları oynamak bazen stresimi atıyor.",
    "Yemek yaparken baharat kullanmayı çok seviyorum.",
    "Bugün gökyüzü bulutsuz ve masmavi görünüyor.",
    "Cüzdanımı evde unuttuğumu otobüste fark ettim.",
    "Kışın kar yağışını izlemekten asla sıkılmam.",
    "Bahçedeki çiçekleri sulamayı unutmamalıyım.",
    "Sessiz bir ortamda kitap okumak en sevdiğim aktivite.",
    "Haftalık planımı yapmadan işe başlamıyorum.",
    "Bugün marketten taze ekmek alıp kahvaltı yaptık.",
    "Bisiklet sürmek hem eğlenceli hem de sağlıklı.",
    "Yeni açılan kafenin dekorasyonu çok modern olmuş.",
    "Yaz tatili için valizimi hazırlamaya başladım.",
    "Bugün öğleden sonra yoğun bir yağmur bekleniyor.",
    "Annemin yaptığı kurabiyelerin kokusu tüm evi sardı.",
    "Yarınki randevumu hatırlatması için alarm kurdum.",
    "Çantamın içine anahtarlarımı bir türlü bulamıyorum.",
    "Ödevlerimi bitirince kendime bir film ödülü vereceğim.",
    "Doğa yürüyüşleri yapmak ruhumu dinlendiriyor.",
    "Bu sabah kahvaltıyı balkonda yapmaya karar verdik.",
    "Şehir hayatının kalabalığı bazen beni yoruyor.",
    "Akşam için hafif bir salata yapmayı düşünüyorum.",
    "Yeni aldığım pantolonun paçalarını yaptırmam gerek.",
    "Havaalanına gitmek için erkenden yola çıkmalıyız.",
    "Geceleri yıldızları izlemek bana sonsuzluğu anımsatıyor.",
    "İş görüşmem beklediğimden çok daha iyi geçti.",
    "Bugün hiç halim yok, sadece uzanmak istiyorum.",
    "Konser bileti bulabildiğim için kendimi şanslı hissediyorum.",
    "Pazar sabahları gazete okumak eski bir alışkanlığım.",
    "Her gün en az iki litre su içmeye çalışıyorum."
]

tokenizer = Tokenizer()
tokenizer.fit_on_texts(texts) # vocabulary oluşturur ve her kelimeyi benzersiz index'e atar
total_words = len(tokenizer.word_index) + 1 # toplam kelime sayısı
# +1 eklenmesinin sebebi word_index indexleri 1'den başlar. normalde indexler 0'dan başladığından eşitlemek için +1 eklenir..!

# n-gram dizileri oluştur. # örn. bugün hava çok güzel. -> input: bugün hava -> hedef: çok vb.
input_sequences = []
for text in texts:
    token_list = tokenizer.texts_to_sequences([text])[0] # cümleyi sayısal indexlere çevirir
    for i in range(1, len(token_list)): # her adımda bir kelime daha ekleyerek n-grams dizileri oluşturur..!
        n_gram_sequences = token_list[:i + 1]
        input_sequences.append(n_gram_sequences)

max_sequence_length = max(len(i) for i in input_sequences) # en uzun dizinin uzunluğu

input_sequences = pad_sequences(input_sequences, max_sequence_length, padding='pre') # padding ile tüm dizileri aynı uzunluğa getirme

X = input_sequences[:, : -1] # son kelime hariç tüm kelimeler girdi
y = input_sequences[:, -1] # son kelime çıktı

y = to_categorical(y, num_classes=total_words) # one hot encoding

embedding_dim = 50
inputs = Input(shape=(max_sequence_length - 1,)) # X'in son kelime harici bütün kelimeleri almasından dolayı -1 gelir
embedding = Embedding(input_dim=total_words, output_dim=embedding_dim)(inputs)
x = LSTM(100, return_sequences=False)(embedding)
outputs = Dense(total_words, activation='softmax')(x)
model = Model(inputs, outputs)
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()
history = model.fit(X, y, epochs=100, batch_size=32, verbose=1)

test_loss, test_acc = model.evaluate(X, y)
print(f'test loss: {test_loss:.3f}, test accuracy: {test_acc*100:.2f}%')

# custom function ile metin üretimi
def generate_text(text, next_words): # text -> başlangıç metni  # next_words -> kaç kelime üreteceği
    for _ in range(next_words):
        token_list = tokenizer.texts_to_sequences([text])[0] # girdi metnini sayısal verilere dönüştür
        token_list = pad_sequences([token_list], maxlen=max_sequence_length - 1, padding='pre') # padding ile uzunluk sabitlenir
        predict = model.predict(token_list, verbose=0)
        predict_word_index = np.argmax(predict, axis=-1) # en yüksek olasılığa sahip kelimenin indexini bul
        predicted_word = tokenizer.index_word[predict_word_index[0]] # indexi kelimeye çevir
        text = text + ' ' + predicted_word # kelimeyi metne ekle
    return text

text = "Bugün hava"
print(generate_text(text, 2))





# region uzay ile ilgili veri setiyle lstm tabanlı metin üretimi
import numpy as np
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.models import Model
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Dense, Embedding, LSTM, Input


space_texts = [
    "Mars yüzeyindeki kızıl toz fırtınalarını izlemek büyüleyici olmalı.",
    "Jüpiter’in devasa kütle çekimi aslında Dünya’yı koruyan bir kalkan gibi.",
    "Satürn’ün halkaları buz parçalarından ve kaya tozlarından oluşuyormuş.",
    "Bu gece teleskopla Ay’daki kraterleri incelemeyi planlıyorum.",
    "Güneş sistemindeki en yüksek dağ aslında Mars’taki Olympus Mons’tur.",
    "Kara deliklerin olay ufkundan hiçbir şeyin kaçamaması ürkütücü bir gerçek.",
    "Andromeda galaksisi bize saniyede yüzlerce kilometre hızla yaklaşıyor.",
    "Astronotların uzayda boylarının birkaç santim uzadığını biliyor muydun?",
    "Uluslararası Uzay İstasyonu’nda bir gün içinde 16 kez gün doğumu izleniyor.",
    "Yıldızların ışığı bize ulaşana kadar aslında o yıldız sönmüş olabilir.",
    "Plüton artık gezegen sayılmasa da gönlümüzde yeri her zaman ayrı.",
    "Venüs’te bir gün, bir yıldan daha uzun sürüyormuş.",
    "Evrenin sürekli genişlediğini düşünmek bazen başımı döndürüyor.",
    "Keşke bir kez olsun Samanyolu’nu ışık kirliliği olmayan bir yerden izlesem.",
    "Güneş, sistemimizdeki toplam kütlenin %99'undan fazlasını oluşturuyor.",
    "Ay tutulması sırasında uydumuzun bakır rengine bürünmesi çok estetik.",
    "Voyager 1 aracı şu an yıldızlararası uzayda yolculuğuna devam ediyor.",
    "Yerçekimsiz ortamda yemek yemenin nasıl bir his olduğunu merak ediyorum.",
    "Güneş patlamaları dünyadaki radyo iletişimini bazen olumsuz etkiliyor.",
    "Nötron yıldızlarından alınan bir kaşık madde milyarlarca ton ağırlığındadır.",
    "Uzayda ses yayılmaz çünkü titreşimleri iletecek bir hava ortamı yoktur.",
    "Mars'ta koloni kurma fikri bilim kurgudan gerçeğe dönüşmek üzere.",
    "Hubble Uzay Teleskobu bize evrenin en eski fotoğraflarını getirdi.",
    "Kuyruklu yıldızların aslında 'kirli kartopları' olduğunu duyunca şaşırmıştım.",
    "James Webb Teleskobu'ndan gelen ilk renkli kareler tek kelimeyle harikaydı.",
    "Yıldız kayması sandığımız şey aslında atmosfere giren küçük meteorlardır.",
    "Titan'ın yüzeyinde sıvı metan gölleri olduğu bilimsel olarak kanıtlandı.",
    "Ay'a ayak basan astronotların ayak izleri rüzgar olmadığı için silinmiyor.",
    "Karanlık madde, evrenin en büyük sırlarından biri olmaya devam ediyor.",
    "Bir gün uzay turizminin herkes için ulaşılabilir olacağını umuyorum.",
    "Güneş’in çekirdek sıcaklığı yaklaşık 15 milyon derece civarındaymış.",
    "Işık hızıyla seyahat edebilseydik Ay’a gitmemiz sadece bir saniye sürerdi.",
    "Kepler teleskobu yaşama uygun binlerce ötegezegen keşfetti.",
    "Mars'ın ince atmosferi nedeniyle orada nefes almak mümkün değil.",
    "Uranüs, güneş sisteminde yan yatmış bir varil gibi dönen tek gezegendir.",
    "Astronot kıyafetlerinin bu kadar ağır ve karmaşık olması inanılmaz.",
    "Güneş fırtınalarının kutuplarda oluşturduğu auroraları görmeyi çok isterim.",
    "Evrende bilinen en soğuk yer Boomerang Nebulası olarak adlandırılıyor.",
    "Süpernova patlamaları, evrendeki ağır elementlerin ana kaynağıdır.",
    "Ay'ın hep aynı yüzünü görüyoruz çünkü kendi etrafında dönme hızıyla eşleşmiş.",
    "Uzay boşluğunda sıcaklık mutlak sıfıra oldukça yakındır.",
    "Göktaşlarının dünyaya çarpma olasılığına karşı sürekli gözlem yapılıyor.",
    "Dünya'nın manyetik alanı bizi güneşin zararlı ışınlarından koruyor.",
    "Kendi galaksimizde bile keşfedilmeyi bekleyen milyarlarca yıldız var.",
    "Uzayda ağlamak zordur çünkü gözyaşları damla olarak yere düşmez.",
    "Mars'taki gün batımları, atmosfer yapısından dolayı mavi renkte görünür.",
    "Satürn o kadar hafiftir ki, yeterince büyük bir su birikintisinde yüzebilir.",
    "Işık yılı bir zaman birimi değil, aslında devasa bir mesafe birimidir.",
    "Yıldızlar arasındaki boşluk sandığımız kadar boş değil, gaz ve tozla dolu.",
    "Kozmik arka plan radyasyonu evrenin başlangıcından kalan bir yankıdır.",
    "Ay'ın çekim kuvveti dünyadaki gelgit olaylarının temel sebebidir.",
    "Gelecekte asteroid madenciliği ekonominin temelini oluşturabilir.",
    "Elon Musk'ın Mars projelerini takip etmek heyecan verici.",
    "Uzay mekikleri kalkış sırasında devasa bir enerji açığa çıkarıyor.",
    "Venüs, güneş sistemindeki en sıcak gezegendir çünkü kalın bulutları var.",
    "Uydular sayesinde bugün dünyanın her yerinden internete erişebiliyoruz.",
    "Astronotların uzay istasyonunda spor yapması kas erimesini önlemek için şart.",
    "Güneş sisteminin dışına çıkan ilk insan yapımı nesne Voyager araçlarıdır.",
    "Nebulalar, yani bulutsular aslında yıldızların doğduğu yerlerdir.",
    "Karanlık enerji, evrenin hızlanarak genişlemesine neden oluyor.",
    "Uzay kıyafetleri astronotları hem aşırı sıcaktan hem de dondurucu soğuktan korur.",
    "Bir kara deliğin içine düşen birine ne olacağı hala bir tartışma konusu.",
    "Güneş'in ömrünün yaklaşık yarısını tamamladığı tahmin ediliyor.",
    "Hafta sonu planetaryuma gidip yıldız gösterisini izlemek istiyorum.",
    "Uzay araştırmaları için harcanan bütçeler aslında teknolojik gelişmeyi hızlandırıyor.",
    "Mars'ta su izlerinin bulunması, yaşam ihtimalini güçlendiriyor.",
    "Galaksiler arasındaki mesafeler hayal gücümüzün çok ötesinde.",
    "Ay'a gitmek, insanlık tarihinin en büyük teknik başarılarından biridir.",
    "Küçük bir teleskopla bile Satürn'ün halkalarını görmek mümkün.",
    "En sevdiğim bilim kurgu filmlerinde genellikle solucan delikleri kullanılıyor.",
    "Güneş tutulması yaşanırken doğanın sessizliğe bürünmesi çok etkileyici.",
    "Jüpiter’in Büyük Kırmızı Lekesi aslında devasa bir fırtınadır.",
    "Uzay istasyonundaki suyun geri dönüştürülerek kullanılması mühendislik harikası.",
    "Yıldızların parlaklığı, onların sıcaklığı ve büyüklüğü hakkında bilgi verir.",
    "Bugün haberlerde yeni bir ötegezegenin keşfedildiğini okudum.",
    "Mars yolculuğu yaklaşık altı ile dokuz ay arasında sürecekmiş.",
    "Uzayda zamanın daha yavaş akması teorisi her zaman ilgimi çekmiştir.",
    "Exoplanet avcıları her geçen gün yeni bir dünya benzeri gezegen buluyor.",
    "Ay yüzeyindeki regolit tozu astronotların ciğerleri için oldukça tehlikeli.",
    "Gökbilimciler radyo teleskopları ile uzayın derinliklerini dinliyorlar.",
    "Samanyolu galaksisi aslında çubuklu sarmal bir yapıya sahip.",
    "Uzay çöpleri gelecekteki görevler için büyük bir risk oluşturuyor.",
    "Uyduların yörüngede kalması için belli bir hızda hareket etmesi gerekir.",
    "Güneş sistemi aslında Samanyolu’nun merkezinde değil, kıyısındadır.",
    "Keşke Mars'tan gelen ilk insanlı görüntüyü canlı yayında izleyebilsem.",
    "Merkür Güneş'e en yakın olmasına rağmen en sıcak gezegen değildir.",
    "Kara deliklerin etrafındaki foton küresi ışığın büküldüğü yerdir.",
    "Uzayda geçirilen uzun süreler kemik yoğunluğunu azaltabiliyor.",
    "Bilim insanları Mars atmosferini oksijene dönüştürmek için çalışıyor.",
    "Kuyruklu yıldızların kuyruğu her zaman Güneş'in tersi yönüne doğru uzar.",
    "Uzay sondaları sayesinde Jüpiter’in uydularını yakından tanıma şansı bulduk.",
    "Galaksi kümeleri birbirlerine kütle çekimi ile bağlıdırlar.",
    "Yıldızların ölümü bazen arkasında bir beyaz cüce bırakır.",
    "Uzay keşifleri sayesinde bugün kullandığımız birçok teknolojiyi kazandık.",
    "Evrende yalnız mıyız sorusu hala cevabını bekleyen en büyük soru.",
    "Mars'taki toz şeytanları (hortumlar) bazen güneş panellerini temizliyor.",
    "Asteroit kuşağı aslında Mars ile Jüpiter arasında yer alır.",
    "Ay'ın çekirdeğinin küçük ve soğuk olduğu düşünülüyor.",
    "Bir pulsar, saniyede yüzlerce kez dönen bir nötron yıldızıdır.",
    "Evrenin gizemlerini çözmek için matematik en güçlü dilimiz.",
    "Uluslararası Uzay İstasyonu, gökyüzünde hızla hareket eden parlak bir yıldız gibi görünüyor.",
    "Mars'taki düşük yerçekimi sayesinde orada smaç basmak çok kolay olurdu.",
    "Venüs'teki asit yağmurları yüzeye ulaşmadan buharlaşıyormuş.",
    "Güneş Sistemi'ndeki tüm gezegenleri Jüpiter'in içine sığdırabiliriz.",
    "Kara deliklerin merkezindeki tekillik noktası fizik kurallarının bittiği yerdir.",
    "Astronotların kasklarındaki vizörler gerçek altınla kaplıdır, bu onları radyasyondan korur.",
    "Ay'ın toprağı aslında barut gibi kokuyormuş, dönen astronotlar öyle söylüyor.",
    "Satürn'ün uydusu Enceladus'ta buzun altında devasa bir okyanus olabilir.",
    "Işık yılı sadece bir mesafe ölçüsüdür, ancak ismi zamanı anımsatıyor.",
    "Güneş her saniye yaklaşık 600 milyon ton hidrojeni helyuma dönüştürüyor.",
    "Uzayda yön duygusu yoktur çünkü 'yukarı' veya 'aşağı' kavramları yerçekimine bağlıdır.",
    "Andromeda ve Samanyolu yaklaşık 4 milyar yıl sonra çarpışacak.",
    "Bir nötron yıldızının yüzeyi o kadar serttir ki elmastan daha dayanıklıdır.",
    "Mars'ta bir kolonide yaşasaydık muhtemelen yeraltı tünellerini kullanırdık.",
    "Uranüs'ün mevsimleri yaklaşık 21 yıl sürüyor, bu çok uzun bir kış demek.",
    "Göktaşlarının atmosfere girerken yanması aslında bizi büyük çarpmalardan koruyor.",
    "Plüton'un yüzeyinde kalp şeklinde devasa bir buz ovası bulunuyor.",
    "Güneş'in ışığı Dünya'ya yaklaşık 8 dakika 20 saniyede ulaşıyor.",
    "Uzay boşluğunda bir metali diğerine dokundurursanız birbirine kaynarlar.",
    "Jüpiter'in uydusu Europa, yaşam arayışı için en heyecan verici yerlerden biri.",
    "Yıldızların renkleri bize sıcaklıklarını anlatır; mavi yıldızlar en sıcak olanlardır.",
    "Astronotlar uzayda uyurken sürüklenmemek için kendilerini bir yere bağlarlar.",
    "Gelecekte ay üssü kurulduğunda oradan roket fırlatmak çok daha az enerji gerektirecek.",
    "Evrenin %95'i hala tam olarak ne olduğunu bilmediğimiz karanlık madde ve enerjiden oluşuyor.",
    "Merkür'ün gündüzleri çok sıcak, geceleri ise dondurucu derecede soğuktur.",
    "Galaksimizin merkezinde 'Sagittarius A*' adında devasa bir kara delik var.",
    "Güneş panelleri uzay araçları için en kritik enerji kaynağıdır.",
    "Bazı yıldızlar kendi etrafında o kadar hızlı döner ki şekilleri basıklaşır.",
    "Mars'taki Curiosity keşif aracı yıllardır bize harika özçekimler gönderiyor.",
    "Ay'da rüzgar olmadığı için bayraklar aslında özel bir tel mekanizmasıyla dik duruyor.",
    "Gezegenlerin yörüngeleri tam daire değil, hafifçe elips şeklindedir.",
    "Voyager araçları üzerlerinde insanlığın seslerini taşıyan altın plaklar bulunduruyor.",
    "Uzayda terlemek tehlikelidir çünkü ter vücudunuzdan damlamaz, birikir.",
    "Güneş'in içine yaklaşık 1.3 milyon tane Dünya sığabilir.",
    "Asteroitlerin içeriğindeki değerli madenler dünya ekonomisini tamamen değiştirebilir.",
    "Venüs, Güneş sisteminde kendi etrafında saat yönünde dönen tek gezegendir.",
    "Solucan delikleri uzayda bir noktadan diğerine kestirme yollar olabilir mi?",
    "Yıldızlararası toz bulutları bazen yeni doğan yıldızların ışığını tamamen kapatır.",
    "Uluslararası Uzay İstasyonu, yaklaşık bir futbol sahası büyüklüğündedir.",
    "Güneş sistemindeki en rüzgarlı gezegen saatte 2000 km hızla esen rüzgarlarıyla Neptün'dür.",
    "Gökbilimciler her yıl binlerce yeni süpernova patlaması gözlemliyor.",
    "Mars'ın iki küçük uydusu var: Phobos ve Deimos.",
    "Ay'da bir gün yaklaşık 29.5 Dünya günü kadar sürer.",
    "Geleceğin astronotları muhtemelen 3D yazıcılarla üretilmiş üslerde yaşayacak.",
    "Uzayda koku vardır; astronotlar bunu 'yanmış biftek' veya 'sıcak metal'e benzetir.",
    "Big Bang teorisi evrenin tek bir noktadan genişlemeye başladığını savunur.",
    "Satürn'ün halkaları aslında milyarlarca yıl önce parçalanmış uyduların kalıntıları olabilir.",
    "Jüpiter o kadar büyüktür ki, diğer tüm gezegenlerin toplamının iki katı kütleye sahiptir.",
    "Kara deliklerin yakınında zamanın yavaşlaması Einstein'ın genel görelilik teorisidir.",
    "Ay'a gönderilen Artemis görevi, oraya ilk kadını indirmeyi hedefliyor.",
    "Uzayda kemik kaybını önlemek için astronotlar günde iki saat direnç egzersizi yapar.",
    "Kepler-452b gezegeni, Dünya'nın daha yaşlı ve daha büyük bir kuzeni olarak bilinir.",
    "Güneş'in manyetik alanı her 11 yılda bir kutuplarını değiştirir.",
    "Halley kuyruklu yıldızı dünyadan 76 yılda bir çıplak gözle görülebiliyor.",
    "Uzay yürüyüşü (EVA) yapmak bir astronotun kariyerindeki en zorlayıcı görevdir.",
    "Evrende Dünya üzerindeki kum tanelerinden daha fazla yıldız olduğu tahmin ediliyor.",
    "Mars'ın atmosferi %95 oranında karbondioksitten oluşur.",
    "Hubble teleskobu olmasaydı evrenin yaşını bu kadar net bilemezdik.",
    "Uzayda bir yangın çıkarsa alevler Dünya'daki gibi değil, küre şeklinde olur.",
    "Nötron yıldızları o kadar yoğundur ki bir çay kaşığı kadarı Everest dağı kadar ağır gelir.",
    "Plüton'un uydusu Charon, Plüton'un neredeyse yarısı büyüklüğündedir.",
    "Güneş'in dış atmosferi olan korona, yüzeyinden çok daha sıcaktır.",
    "Astronotların kıyafetleri basınçlıdır, aksi takdirde vücut sıvıları kaynamaya başlardı.",
    "Yerçekimsel merceklenme, uzaktaki galaksilerin ışığını dev kütlelerle bükme olayıdır.",
    "Uzayda bitki yetiştirmek (astrobotanik), uzun süreli görevlerin anahtarıdır.",
    "Merkür'ün yüzeyi tıpkı Ay gibi kraterlerle doludur.",
    "Güneş fırtınaları sırasında oluşan kuzey ışıkları aslında bir doğa harikasıdır.",
    "Evrenin toplam yaşı yaklaşık 13.8 milyar yıl olarak hesaplanmıştır.",
    "Işık kirliliği nedeniyle şehirlerde yaşayan çocuklar Samanyolu'nu hiç göremiyor.",
    "Mars'ta suyun sıvı halde akması için atmosfer basıncının artması gerekir.",
    "Keşif araçlarının lastikleri Mars'ın keskin kayalarına dayanacak şekilde tasarlanıyor.",
    "Uzayda bir silah ateşlerseniz mermi sonsuza kadar (bir şeye çarpana dek) gider.",
    "Güneş lekeleri, Güneş'in yüzeyindeki nispeten 'soğuk' bölgelerdir.",
    "Spagettileşme, bir kara deliğe giren nesnenin boyuna uzayıp incelmesi olayıdır.",
    "Samanyolu galaksisi yaklaşık 100 bin ışık yılı çapındadır.",
    "Ay'daki sarsıntılara 'ay depremi' (moonquake) denir.",
    "Gelecekte nükleer füzyon roketleri ile Mars'a gitmek birkaç haftaya düşebilir.",
    "Satürn'ün uydusu Titan'da atmosfer basıncı Dünya'dakinden daha yüksektir.",
    "Uydular sayesinde fırtınaları ve tayfunları önceden haber alabiliyoruz.",
    "Uzayda her şey hareket halindedir; hiçbir şey tam olarak durmaz.",
    "Kara delikleri doğrudan göremeyiz, sadece etraflarındaki maddeye etkilerini görürüz.",
    "James Webb Teleskobu, Hubble'dan çok daha uzağı ve geçmişi görebiliyor.",
    "Güneş Sistemi'ndeki en büyük kanyon Mars'taki Valles Marineris'tir.",
    "Astronotlar dünyaya döndüklerinde denge kurmakta zorluk çekebilirler.",
    "Venüs'te bir yanardağ patlaması izlemek oldukça ekstrem bir deneyim olurdu.",
    "Gökbilimciler her gün gökyüzünü tarayarak tehlikeli asteroitleri arıyor.",
    "Evrenin geometrisi 'düz' olarak kabul edilmektedir.",
    "Yıldız tozundan oluştuğumuz gerçeği bilimsel bir dayanaktır.",
    "Mars atmosferinde oksijen üretmek için MOXIE adlı bir cihaz test ediliyor.",
    "Ay'ın çekirdeği zamanla soğuduğu için Ay aslında yavaşça büzüşüyor.",
    "Jüpiter'in uydusu Io, güneş sistemindeki en volkanik yerdir.",
    "Uzayda yönünüzü kaybetmemek için yıldız haritalarını kullanmalısınız.",
    "Kozmik ışınlar uzay istasyonundaki elektronik cihazlara zarar verebilir.",
    "Süper kütleli kara delikler genellikle galaksilerin merkezinde bulunur.",
    "Evrenin sonu hakkında 'Büyük Donma' gibi çeşitli teoriler vardır.",
    "Yarın gece teleskopla Jüpiter'in uydularını görmeye çalışacağım.",
    "Uzay yarışının kazananı aslında bilimsel merakın kendisidir.",
    "Güneş'in ışığı sönerse bunu ancak 8 dakika sonra fark edebiliriz.",
    "Uzayda hayatta kalmak için teknolojiye %100 bağımlıyız.",
    "Bir sonraki tam güneş tutulmasını şimdiden takvimime işaretledim.",
    "Evrenin genişleme hızı, beklediğimizden çok daha yüksek görünüyor.",
    "Mars'taki gün süresi (Sol), Dünya'daki bir günden sadece 40 dakika daha uzundur.",
    "Venüs'ün yüzey basıncı, okyanusun 900 metre derinliğindeki basınca eşittir.",
    "Güneş Sistemi'ndeki en büyük kraterlerden biri Ay'ın güney kutbundaki Aitken Havzası'dır.",
    "Kara delikler ışığı bile yuttuğu için aslında 'görünmez' nesnelerdir.",
    "Astronotların kıyafetleri içindeki soğutma sistemi, vücut ısısını dengede tutar.",
    "Uluslararası Uzay İstasyonu'nda içme suyu, idrarın arıtılmasıyla elde edilir.",
    "Satürn'ün en büyük uydusu Titan, kalın bir atmosfere sahip olan tek uydudur.",
    "Işık yılı mesafesi yaklaşık 9.5 trilyon kilometredir.",
    "Güneş'in kütlesi zamanla enerjiye dönüştüğü için Güneş aslında yavaşça hafifliyor.",
    "Uzayda 'yukarı' kavramı olmadığı için astronotların kafası sık sık karışabilir.",
    "Samanyolu galaksisi yaklaşık 13.6 milyar yaşındadır.",
    "Nötron yıldızlarının manyetik alanları Dünya'nınkinden trilyonlarca kat daha güçlüdür.",
    "Mars'ta kurulacak ilk seralarda bitki yetiştirmek insanlık için hayati önem taşıyor.",
    "Neptün'ün uydusu Triton, gezegeninin dönüş yönünün tersine hareket eder.",
    "Göktaşları çarptığında Ay yüzeyinde oluşan tozlar cam kadar keskindir.",
    "Plüton'un yörüngesi o kadar eliptiktir ki bazen Neptün'den daha yakın olur.",
    "Güneş'in merkezinde saniyede 4 milyon ton madde enerjiye dönüşür.",
    "Uzay boşluğunda iki pürüzsüz metal yüzey temas ettiğinde kalıcı olarak birleşir.",
    "Jüpiter'in uydusu Ganymede, Merkür gezegeninden daha büyüktür.",
    "Kırmızı dev aşamasına gelen bir yıldız, etrafındaki gezegenleri yutabilir.",
    "Astronotlar uzay yürüyüşünden önce saf oksijen soluyarak kanlarını temizlerler.",
    "Ay'ın uzak tarafı (karanlık yüzü) aslında Güneş ışığı alır ama biz görmeyiz.",
    "Karanlık madde ışığı yansıtmaz, emmez veya yaymaz; sadece kütle çekimiyle fark edilir.",
    "Merkür'ün demir çekirdeği, gezegenin toplam hacminin büyük bir kısmını kaplar.",
    "Galaksimizin merkezindeki kara deliğin etrafında binlerce yıldız hızla döner.",
    "Güneş'ten gelen yüklü parçacıklar uyduların elektronik devrelerini yakabilir.",
    "Bazı yıldızlar ömürlerinin sonunda o kadar büyür ki 'hiperdev' olarak adlandırılırlar.",
    "Mars'taki Perseverance aracı, antik yaşam izlerini aramak için örnekler topluyor.",
    "Ay'da atmosfer olmadığı için sıcaklık gölgede aniden düşer, güneşte ise yükselir.",
    "Gezegenlerin isimleri genellikle antik Roma ve Yunan tanrılarından gelir.",
    "Voyager araçları şu an güneş rüzgarının bittiği heliopoz bölgesini geçmiştir.",
    "Uzayda koku alma duyusu, mukoza şişmesi nedeniyle geçici olarak azalır.",
    "Güneş'in hacmi, içine bir milyon tane Dünya sığacak kadar geniştir.",
    "Asteroit madenciliği için şimdiden özel şirketler kurulmaya başlandı.",
    "Venüs'te güneş batıdan doğar ve doğudan batar.",
    "Beyaz delikler, kara deliklerin tam tersi olarak madde püskürten teorik yapılardır.",
    "Yıldızlararası uzayda atomlar arasındaki mesafe santimetre başına sadece bir atomdur.",
    "Uluslararası Uzay İstasyonu, Dünya etrafındaki turunu 90 dakikada tamamlar.",
    "Neptün'ün masmavi rengi, atmosferindeki metan gazından kaynaklanır.",
    "Gökbilimciler 'altın sarısı' bölgelerde yeni yıldız oluşumlarını gözlemliyor.",
    "Mars'ın uydusu Phobos, her yüzyılda gezegenine iki metre daha yaklaşır.",
    "Ay'da tartılsaydınız, kütle çekimi az olduğu için kilonuzun altıda birini görürdünüz.",
    "Gelecekte Mars'a gidecek astronotlar radyasyona karşı özel kalkanlar kullanacak.",
    "Uzayda ses yoktur çünkü sesi iletecek moleküller birbirinden çok uzaktır.",
    "Büyük Patlama (Big Bang) aslında bir patlama değil, aniden bir genişlemedir.",
    "Satürn'ün halkaları teleskopla bakıldığında katı bir disk gibi görünür ama değildir.",
    "Jüpiter, Güneş Sistemi'nin elektrik süpürgesi gibi kuyruklu yıldızları kendine çeker.",
    "Olay ufku, bir kara deliğin geri dönüşü olmayan sınır noktasıdır.",
    "Artemis programı ile Ay'da kalıcı bir insan varlığı oluşturulması hedefleniyor.",
    "Uzayda astronotların omurga diskleri arasındaki boşluk genişlediği için boyları uzar.",
    "Güneş Sistemi'mize en yakın yıldız sistemi Proxima Centauri'dir.",
    "Güneş'in korona tabakası, güneş tutulması sırasında muazzam bir taç gibi görünür.",
    "Kuyruklu yıldızların çekirdeği buz, kaya ve organik bileşiklerden oluşur.",
    "Uzay yürüyüşü sırasında astronotların yorulmasının ana sebebi kıyafetin sertliğidir.",
    "Evrende görülebilir milyarlarca galaksinin her biri milyarlarca yıldız içerir.",
    "Mars'ta gökyüzü pembe-turuncu, gün batımı ise mavidir.",
    "Hubble, evrenin genişleme hızını ölçmemize yardımcı olan en önemli araçtır.",
    "Uzayda su içmek için pipetli ve kapalı torbalar kullanılması zorunludur.",
    "Nötron yıldızları o kadar hızlı döner ki bir deniz feneri gibi ışık saçar.",
    "Plüton'un yüzeyinde donmuş nitrojen buzulları ve dağlar bulunur.",
    "Güneş fırtınaları sırasında astronotlar istasyonun daha korunaklı kısımlarına geçer.",
    "Uzay kıyafetlerinin dış katmanı mikrometeor çarpmalarına karşı dayanıklıdır.",
    "Kütle çekimsel dalgalar, uzay-zaman dokusundaki dalgalanmalardır.",
    "Uzayda tarım yapmak için topraksız tarım (hidroponik) yöntemleri geliştiriliyor.",
    "Merkür, Güneş etrafındaki dönüşünü sadece 88 günde tamamlar.",
    "Güneş sistemindeki cüce gezegenler arasında Eris, Plüton'dan daha kütlelidir.",
    "Evrenin ısısı mutlak sıfırın yaklaşık 2.7 derece üzerindedir.",
    "Işık kirliliği, astronomik gözlemlerin önündeki en büyük engellerden biridir.",
    "Mars'ta bir zamanlar nehirlerin aktığına dair çok net jeolojik kanıtlar var.",
    "Sonda araçları, gezegenlerin atmosferine girerek veri toplar.",
    "Uzayda bir gözyaşı damlası yüzünüze yapışır ve kendiliğinden düşmez.",
    "Güneş lekeleri, manyetik alanın çok güçlü olduğu ve ısıyı engellediği yerlerdir.",
    "Spagettileşme etkisinde ayaklarınız başınızdan daha güçlü bir çekime maruz kalır.",
    "Samanyolu'nun komşu galaksisi Andromeda ile birleşmesine daha çok zaman var.",
    "Ay'dan getirilen taşlar, Dünya'nın ve Ay'ın ortak bir geçmişi olduğunu gösteriyor.",
    "Gelecekte uzay asansörü inşa etmek, fırlatma maliyetlerini %99 oranında düşürebilir.",
    "Titan'da yerçekimi o kadar azdır ki kollarınıza kanat takıp uçabilirsiniz.",
    "Uyduların yörüngeden çıkıp dünyaya düşmemesi için belirli bir hızda kalması gerekir.",
    "Uzayda yemekler genellikle kurutulmuş ve vakumlanmış paketlerde saklanır.",
    "Kara deliklerin birleşmesi uzay-zamanda devasa enerji dalgaları yaratır.",
    "James Webb, kızılötesi ışığı kullanarak toz bulutlarının arkasındaki yıldızları görür.",
    "Güneş Sistemi'ndeki en derin kanyon olan Valles Marineris 4000 km uzunluğundadır.",
    "Astronotlar Dünya'ya döndüğünde bazen ellerindeki bardağı bırakıp düşmesini izlerler.",
    "Venüs'ün yüzeyinde kurşun bile eriyebilecek kadar yüksek bir ısı vardır.",
    "Gökbilimciler her gün binlerce radyo sinyalini analiz ederek akıllı yaşam arıyor.",
    "Evrenin dokusu karanlık enerji nedeniyle her geçen saniye daha hızlı genişliyor.",
    "Yıldızların ölümüyle saçılan maddeler, yeni gezegenlerin yapı taşlarını oluşturur.",
    "Mars'taki kutup buzulları karbon karbondioksit buzundan ve su buzundan oluşur.",
    "Ay her yıl Dünya'dan yaklaşık 3.8 santimetre uzaklaşıyor.",
    "Jüpiter'in halkaları o kadar incedir ki Dünya'dan görülmesi çok zordur.",
    "Uzayda yön tayini yapmak için en güvenilir yöntem pulsar yıldızlarını izlemektir.",
    "Kozmik ışınlar, DNA üzerinde mutasyonlara neden olabilecek kadar güçlüdür.",
    "Süper kütleli kara deliklerin kütlesi Güneş'in milyonlarca katı olabilir.",
    "Evrenin sonu hakkında 'Büyük Çöküş' teorisi, kütle çekiminin galip gelmesini savunur.",
    "Bugün teleskobumun lensini temizledim, gece Satürn'ü izleyeceğim.",
    "Uzay keşifleri, insanlığın sınırlarını zorlayan en büyük maceradır.",
    "Güneş olmasaydı gezegenimiz karanlık ve donmuş bir kaya parçası olurdu.",
    "Uzayda tuvalet ihtiyacını gidermek için hava akımlı özel sistemler kullanılır.",
    "Bir sonraki meteor yağmurunu izlemek için şehirden uzak bir kamp yeri buldum.",
    "Evrenin %68'inin karanlık enerjiden oluştuğu tahmin ediliyor.",
    "Mars'taki düşük yerçekimi nedeniyle orada yürümek zıplamaya benzer.",
    "Venüs, Güneş Sistemi'nin en parlak ikinci doğal nesnesidir.",
    "Güneş Sistemi'ndeki en büyük volkan olan Olympus Mons, Everest'ten üç kat daha yüksektir.",
    "Kara deliklerin etrafındaki ışık bükülmesi, uzay-zamanın fiziksel bir kanıtıdır.",
    "Astronotlar uzayda koku alma yetilerini bir süreliğine kaybedebilirler.",
    "Uluslararası Uzay İstasyonu'nda astronotlar günde 1.5 saatten fazla egzersiz yapar.",
    "Satürn'ün halkaları çoğunlukla su buzundan oluşur ve parlar.",
    "Işık yılı, ışığın boşlukta bir dünya yılı boyunca katettiği mesafedir.",
    "Güneş'in kütle çekimi, sekiz gezegeni ve sayısız gök cismini bir arada tutar.",
    "Uzayda 'yukarı' veya 'aşağı' olmadığı için uyumak bazen çok tuhaf hissettirir.",
    "Samanyolu galaksisi, Laniakea adı verilen devasa bir galaksi süper kümesinin parçasıdır.",
    "Nötron yıldızları, devasa yıldızların süpernova patlamasından sonraki kalıntılarıdır.",
    "Mars'ta bitki yetiştirmek için regolit adı verilen toprağın kimyasal olarak temizlenmesi gerekir.",
    "Neptün'ün uydusu Triton, güneş sistemindeki en soğuk cisimlerden biridir.",
    "Göktaşları Ay'a çarptığında kraterler oluşturur çünkü Ay'ın koruyucu bir atmosferi yoktur.",
    "Plüton'un beş uydusu vardır ve en büyüğü Charon'dur.",
    "Güneş'in çekirdek sıcaklığı, nükleer füzyonun gerçekleşmesi için yeterince yüksektir.",
    "Uzayda iki pürüzsüz metalin birbirine kaynamasına 'soğuk kaynak' denir.",
    "Jüpiter'in uydusu Callisto, güneş sistemindeki en eski yüzeye sahip cisim olabilir.",
    "Kırmızı cüce yıldızlar, evrendeki en yaygın ve en uzun ömürlü yıldız tipidir.",
    "Astronotlar uzay yürüyüşü sırasında özel idrar toplama aparatları kullanırlar.",
    "Ay'ın çekim kuvveti dünyadaki deniz seviyelerini günde iki kez değiştirir.",
    "Karanlık madde, galaksilerin parçalanmadan bir arada durmasını sağlayan gizli bir tutkaldır.",
    "Merkür'ün yüzeyinde demir bolluğu olduğu için rengi koyu gridir.",
    "Galaksimizin merkezindeki kara delik, Güneş'ten 4 milyon kat daha ağırdır.",
    "Güneş'ten gelen radyasyon, uzaydaki uyduların ömrünü kısaltan en büyük faktördür.",
    "Bazı yıldızlar ömürlerini tamamladığında muazzam bir parlaklıkla infilak eder.",
    "Mars'taki InSight sondası, gezegenin iç yapısını sismik dalgalarla inceledi.",
    "Ay'da öğle vakti sıcaklık 120 santigrat dereceye kadar çıkabilir.",
    "Gezegenlerin yörüngeleri Newton'un kütle çekim kanunlarına göre şekillenir.",
    "Voyager 2, dört dış gezegeni de (Jüpiter, Satürn, Uranüs, Neptün) ziyaret eden tek araçtır.",
    "Uzayda vücut sıvıları yukarı doğru hareket ettiği için yüzler 'pofuduk' görünür.",
    "Güneş'in yaydığı enerji, dünyadaki yaşamın temel enerji kaynağıdır.",
    "Asteroitlerin çarpma riskini azaltmak için saptırma teknolojileri geliştiriliyor.",
    "Venüs'te bir gün, gezegenin Güneş etrafındaki bir tam turundan daha uzundur.",
    "Beyaz delikler, kara deliklerin matematiksel bir tersi olarak kuramsal bir olasılıktır.",
    "Yıldızlararası uzayda seyahat etmek, mevcut teknolojimizle binlerce yıl sürer.",
    "Uluslararası Uzay İstasyonu, saatte yaklaşık 28.000 kilometre hızla hareket eder.",
    "Neptün, teleskopla keşfedilmeden önce matematiksel hesaplamalarla bulunmuştur.",
    "Gökbilimciler, yıldızların ışık tayfını inceleyerek hangi elementlerden oluştuklarını anlarlar.",
    "Mars'ın uyduları Phobos ve Deimos aslında yakalanmış asteroitler olabilir.",
    "Ay'ın yerçekimi, Dünya'nın kendi ekseni etrafındaki dönüşünü yavaşlatır.",
    "Gelecekteki uzay madencileri, asteroitlerden su ve değerli metaller çıkaracak.",
    "Uzayda ses yoktur ama radyo dalgaları yardımıyla iletişim kurulabilir.",
    "Büyük Patlama'dan hemen sonra evren çok sıcak ve yoğun bir çorba gibiydi.",
    "Satürn'ün halkaları aslında milyarlarca buz ve kaya parçasından oluşur.",
    "Jüpiter'in devasa manyetik alanı, gezegenin etrafında radyasyon kuşakları oluşturur.",
    "Olay ufkunu geçen bir cisim için zaman, dışarıdaki bir gözlemciye göre durmuş gibi görünür.",
    "Artemis görevinde kullanılacak Orion uzay aracı, derin uzay yolculukları için tasarlandı.",
    "Uzayda yerçekimi azlığı nedeniyle astronotların kalp kasları zayıflayabilir.",
    "Güneş Sistemi'ne en yakın yıldız olan Proxima Centauri bir kırmızı cücedir.",
    "Güneş'in korona tabakası, güneşin yüzeyinden milyonlarca kilometre uzağa uzanır.",
    "Kuyruklu yıldızlar, Güneş'e yaklaştıklarında buharlaşarak parlak bir kuyruk oluştururlar.",
    "Uzay yürüyüşü sırasında astronotların en büyük düşmanı aşırı sıcaklık değişimleridir.",
    "Evrendeki galaksilerin çoğu sarmal, eliptik veya düzensiz şekillerdedir.",
    "Mars'ta atmosfer çok ince olduğu için sesler Dünya'dakinden daha boğuk iletilir.",
    "Hubble, uzak galaksilerin bizden uzaklaşma hızını ölçerek evrenin genişlediğini kanıtladı.",
    "Uzayda yemeklerin dökülmemesi için her şeyin yapışkan veya sulu olması tercih edilir.",
    "Nötron yıldızları, evrenin en yoğun atom çekirdekleri gibi davranırlar.",
    "Plüton, Kuiper Kuşağı adı verilen buzlu cisimler bölgesinin en bilinen üyesidir.",
    "Güneş fırtınaları sırasında yayılan parçacıklar, uçak yolcuları için radyasyon riski oluşturabilir.",
    "Uzay kıyafetleri, astronotu vakum etkisinden korumak için basınçlı hava ile şişirilir.",
    "Kütle çekimsel dalgalar, iki kara deliğin çarpışması gibi dev olaylarla oluşur.",
    "Uzayda hidroponik sistemler sayesinde taze marul ve turp yetiştirilebildi.",
    "Merkür, Güneş'e o kadar yakındır ki gökyüzünde Güneş devasa görünür.",
    "Güneş sistemindeki en uzak cüce gezegenlerden biri olan Sedna'nın yörüngesi çok geniştir.",
    "Evrenin sıcaklığı, Big Bang'den bu yana sürekli olarak düşmektedir.",
    "Işık kirliliği, sadece astronomiyi değil gece yaşayan hayvanları da olumsuz etkiler.",
    "Mars'taki kanyonlar, Dünya'daki Büyük Kanyon'dan çok daha derin ve geniştir.",
    "Sonda araçları, iniş yapmadan önce yörüngeden yüksek çözünürlüklü haritalar çıkarır.",
    "Uzayda bir bardak suyu boşaltırsanız, yüzey gerilimi nedeniyle su küre haline gelir.",
    "Güneş lekelerinin sayısı, 11 yıllık bir döngü içinde artar ve azalır.",
    "Spagettileşme teorisi, kara deliğin merkezine yaklaştıkça artan çekim farkını açıklar.",
    "Samanyolu'nun merkezinde yıldız yoğunluğu, galaksinin kenarlarına göre çok daha fazladır.",
    "Ay'ın yüzeyindeki kraterlerin çoğu milyarlarca yıl önce oluşmuştur.",
    "Gelecekte plazma motorları sayesinde Mars'a yolculuk süresi yarı yarıya azalabilir.",
    "Titan'daki metan nehirleri, Dünya'daki su döngüsüne benzer bir döngü oluşturur.",
    "Uydular, Dünya'nın kütle çekimi ile merkezkaç kuvveti dengelendiğinde yörüngede kalır.",
    "Uzayda yemek yeme süreci, kırıntıların cihazlara kaçmaması için çok dikkatli yönetilir.",
    "Kara deliklerin birleşmesi sonucunda açığa çıkan enerji, tüm yıldızların ışığından fazladır.",
    "James Webb, evrenin ilk yıldızlarının doğuşunu görmek için tasarlanmış bir zaman makinesidir.",
    "Güneş Sistemi'ndeki en yüksek uçurumlar Uranüs'ün uydusu Miranda'da bulunur.",
    "Astronotlar Dünya'ya döndüklerinde yerçekimine alışmak için fizik tedavi görürler.",
    "Venüs'ün atmosferi o kadar kalındır ki yüzeyden gökyüzü asla görünmez.",
    "Gökbilimciler, ötegezegenlerin atmosferinde yaşam belirtisi olabilecek gazlar arıyorlar.",
    "Evrenin genişlemesi, galaksiler arasındaki mesafenin artması anlamına gelir.",
    "Yıldızlar, ömürlerinin sonunda süpernova olarak patlayıp ağır metalleri uzaya saçar.",
    "Mars'taki buzullar erirse, tüm gezegenin yüzeyi birkaç metre suyla kaplanabilir.",
    "Ay, Dünya'nın eksen eğikliğini sabitleyerek iklimlerin kararlı kalmasını sağlar.",
    "Jüpiter'in uydusu Europa'nın buz altı okyanusu, tuzlu su içermektedir.",
    "Uzayda yönünüzü bulmak için jiroskoplar ve yıldız takipçileri kullanılır.",
    "Kozmik ışınlar, Güneş Sistemi dışından gelen yüksek enerjili parçacıklardır.",
    "Süper kütleli kara delikler, galaksilerin oluşumu ve evriminde anahtar rol oynar.",
    "Evrenin sonu hakkında 'Büyük Yırtılma' teorisi, her şeyin atomlarına ayrılacağını öngörür.",
    "Bugün gökyüzü çok net, teleskopla Ay'ın denizlerini inceleyeceğim.",
    "Uzay araştırmaları, insanlığın ortak geleceği için yapılan en önemli yatırımdır.",
    "Güneş, her saniye devasa miktarda enerjiyi radyasyon olarak uzaya yayar.",
    "Uzayda kişisel temizlik için su kullanmak yerine ıslak mendiller tercih edilir.",
    "Bir sonraki Perseid meteor yağmurunu izlemek için şehirden uzaklaşacağım.",
    "Kozmik toz bulutları, yeni yıldızların oluşması için gerekli olan hammaddeyi sağlar.",
    "Mars'taki düşük yerçekimi, astronotların hareket ederken daha az enerji harcamasına neden olur.",
    "Venüs'ün atmosferindeki sülfürik asit bulutları, güneş ışığını yansıtarak gezegeni çok parlak gösterir.",
    "Güneş Sistemi'ndeki en büyük krater olan Hellas Planitia, Mars'ın güney yarım küresinde bulunur.",
    "Kara deliklerin içindeki kütle çekimi o kadar güçlüdür ki ışık bile bir hapishanedeymiş gibi kalır.",
    "Astronotlar uzayda radyasyona maruz kaldıklarında bazen gözlerini kapattıklarında ışık parlamaları görürler.",
    "Uluslararası Uzay İstasyonu'nun dış yüzeyi, aşırı sıcaklık farklarına dayanacak şekilde yalıtılmıştır.",
    "Satürn'ün halkaları sadece birkaç on metre kalınlığındadır, yani oldukça incedir.",
    "Işık yılı, evrenin devasa ölçeğini anlamamıza yardımcı olan bir cetvel gibidir.",
    "Güneş'in manyetik döngüsü, dünyadaki iklim modelleri üzerinde dolaylı etkilere sahip olabilir.",
    "Uzayda uyumak için kullanılan tulumlar, astronotların havada süzülüp etrafa çarpmasını engeller.",
    "Samanyolu galaksisi, merkezinde çok eski yıldızlardan oluşan devasa bir şişkinliğe sahiptir.",
    "Nötron yıldızlarının yüzeyinde 'dağlar' olabilir, ancak bunlar sadece birkaç milimetre yüksekliğindedir.",
    "Mars'ta kurulacak bir üs için radyasyondan korunmak amacıyla toprak altına sığınaklar yapılabilir.",
    "Neptün'ün uydusu Proteus, düzensiz şekilli olmasına rağmen oldukça büyük bir kütleye sahiptir.",
    "Göktaşları Ay yüzeyine çarptığında oluşan ısı, Ay toprağını mikroskobik cam küreciklerine dönüştürür.",
    "Plüton'un yüzey sıcaklığı yaklaşık eksi 230 santigrat derece civarındadır.",
    "Güneş'in hidrojen yakıtı bittiğinde, bir kırmızı deve dönüşerek genişleyecektir.",
    "Uzayda 'soğuk kaynak' olayı, vakum ortamında atomların aralarında engel bulamamasından kaynaklanır.",
    "Jüpiter'in uydusu Amalthea, güneş sistemindeki en kırmızımsı nesnelerden biri olarak bilinir.",
    "Kırmızı cüceler o kadar yavaş enerji tüketirler ki trilyonlarca yıl hayatta kalabilirler.",
    "Astronotlar uzayda tuvalet eğitimi için yerdeki simülatörlerde haftalarca pratik yaparlar.",
    "Ay'ın çekimi olmasaydı, Dünya kendi etrafında çok daha hızlı döner ve günler çok kısa olurdu.",
    "Karanlık maddeyi doğrudan tespit edemediğimiz için ona 'hayalet madde' de denir.",
    "Merkür'ün yüzeyinde 'scarps' adı verilen devasa uçurumlar, gezegen soğurken büzüştüğü için oluşmuştur.",
    "Galaksimizin merkezindeki kara deliğe yakın yıldızlar, saatte milyonlarca kilometre hızla hareket eder.",
    "Güneş fırtınaları, Dünya'nın iyonosfer tabakasında elektrik akımları oluşturabilir.",
    "Bazı yıldızlar ikili sistemler oluşturur ve birbirlerinin etrafında dans eder gibi dönerler.",
    "Mars'taki Opportunity aracı, planlanandan 15 yıl daha fazla çalışarak rekor kırmıştır.",
    "Ay'da su buzu olduğu kesinleşti, bu da gelecekteki üsler için oksijen ve yakıt kaynağı demektir.",
    "Gezegenlerin yörünge hızları, Güneş'e yaklaştıkça artar ve uzaklaştıkça azalır.",
    "Voyager 1 üzerindeki radyoizotop termoelektrik jeneratörleri hala elektrik üretmeye devam ediyor.",
    "Uzayda koku alma duyusunun değişmesi, yerçekimsiz ortamda kanın baş bölgesine toplanmasındandır.",
    "Güneş'in yaydığı fotonlar, çekirdekten yüzeye çıkmak için binlerce yıl harcarlar.",
    "Asteroitlerin birçoğu aslında katı bir kaya değil, birbirine kütle çekimiyle tutunan moloz yığınlarıdır.",
    "Venüs'ün yüzeyine inen Sovyet Venera sondaları, yüksek ısı nedeniyle sadece birkaç saat dayanabilmiştir.",
    "Beyaz delikler, zamanın geriye doğru aktığı bir matematiksel modelleme olarak düşünülür.",
    "Yıldızlararası yolculuk için 'güneş yelkenleri' gibi alternatif itki sistemleri üzerinde çalışılıyor.",
    "Uluslararası Uzay İstasyonu, Dünya'nın en pahalı tek yapısı olarak kabul edilir.",
    "Neptün'ün atmosferinde saniyede 600 metre hıza ulaşan süpersonik rüzgarlar eser.",
    "Gökbilimciler, yıldızların titremesini izleyerek onların etrafındaki gezegenleri bulabilirler.",
    "Mars'ın uydusu Phobos, gelecekte kütle çekimi nedeniyle parçalanıp Mars etrafında bir halka oluşturacak.",
    "Ay'ın ekseni etrafında dönme süresi ile Dünya etrafında dönme süresi tamamen aynıdır.",
    "Gelecekte asteroitlerden çıkarılacak platin ve altın, dünya piyasalarını kökten etkileyebilir.",
    "Uzayda ses iletimi mümkün değildir ancak elektromanyetik dalgalar her yere yayılabilir.",
    "Büyük Patlama'dan kalan radyasyon, eski televizyonların karlı ekranlarındaki parazitin bir kısmını oluşturur.",
    "Satürn'ün halkaları büyük oranda saf sudan oluştuğu için güneş ışığını mükemmel yansıtır.",
    "Jüpiter'in uydusu Europa'nın buz tabakası altında Dünya'daki toplam sudan daha fazlası olabilir.",
    "Olay ufkuna yaklaşan bir saat, dışarıdaki bir gözlemciye göre giderek daha yavaş tik tak yapar.",
    "Artemis 2 görevi, insanları Ay'ın etrafından dolaştırıp geri getirecek olan ilk modern görevdir.",
    "Uzayda uzun süre kalan astronotların göz kürelerinin şekli, sıvı basıncı nedeniyle değişebilir.",
    "Güneş Sistemi'ndeki en yakın yıldız olan Proxima b gezegeni, yaşam kuşağında yer alıyor.",
    "Güneş'in korona tabakasındaki sıcaklık, yüzey sıcaklığından yaklaşık 300 kat daha fazladır.",
    "Kuyruklu yıldızlar, Güneş Sistemi'nin oluşumundan kalan bozulmamış fosiller gibidir.",
    "Uzay yürüyüşü yapan astronotlar, güneşin altına geçtiklerinde aniden 120 derece sıcaklıkla karşılaşırlar.",
    "Evrendeki galaksiler, 'kozmik ağ' adı verilen ipliksi yapılar boyunca dizilmişlerdir.",
    "Mars'ta gökyüzünün mavi değil de sarımtırak olması, havadaki ince toz parçacıklarından dolayıdır.",
    "Hubble'ın çektiği 'Pillars of Creation' fotoğrafı, yıldızların doğum sürecini en net gösteren karedir.",
    "Uzayda yemeklerin tadı daha az alınır, bu yüzden astronotlar genellikle çok baharatlı yemekler isterler.",
    "Nötron yıldızları, süpernova patlamasından sonra kendi üzerine çöken dev yıldız çekirdekleridir.",
    "Plüton, Güneş etrafındaki bir tam turunu yaklaşık 248 Dünya yılında tamamlar.",
    "Güneş patlamaları, Dünya'nın manyetik alanında fırtınalar kopararak elektrik kesintilerine yol açabilir.",
    "Uzay kıyafetlerinin içindeki oksijen basıncı, astronotun hareket kabiliyetini kısıtlayacak kadar yüksektir.",
    "Kütle çekimsel merceklenme, Einstein'ın uzayın bükülebileceği öngörüsünü kanıtlayan bir fenomendir.",
    "Uzayda yetiştirilen ilk çiçek olan zinya, bitkilerin yerçekimsiz ortamda da açabileceğini gösterdi.",
    "Merkür, Güneş Sistemi'ndeki en küçük gezegen olmasına rağmen inanılmaz yoğun bir çekirdeğe sahiptir.",
    "Güneş sistemindeki en yavaş dönen gezegen Venüs'tür; bir günü bir yılından uzundur.",
    "Evrenin genişlemesi galaksileri birbirinden uzaklaştırırken, kütle çekimi onları gruplar halinde tutar.",
    "Işık kirliliğini azaltmak için tasarlanan 'karanlık gökyüzü parkları' amatör astronomlar için bir cennettir.",
    "Mars'taki Jezero krateri, milyarlarca yıl önce bir nehir deltasına ev sahipliği yapıyordu.",
    "Sonda araçları, bir gezegenin kütle çekimini kullanarak hızlanmak için 'sapan etkisi' yöntemini kullanır.",
    "Uzayda bir su damlası, yerçekimi olmadığı için mükemmel bir küre formuna bürünür.",
    "Güneş döngüsünün 'solar minimum' döneminde, güneş lekeleri neredeyse tamamen kaybolur.",
    "Spagettileşme sırasında atomlar arasındaki bağlar, kütle çekim farkına dayanamayarak kopar.",
    "Samanyolu galaksisi, milyarlarca yıl önce başka küçük galaksileri yutarak büyümüştür.",
    "Ay'ın yüzeyindeki 'deniz' adı verilen koyu bölgeler aslında antik lav ovalarıdır.",
    "Gelecekte iyon motorları, çok az yakıt tüketerek uzay araçlarını inanılmaz hızlara ulaştırabilir.",
    "Titan'ın yüzeyinde kum tepeleri vardır ancak bu kumlar buz ve organik bileşiklerden oluşur.",
    "Uydular, GPS verilerini santimetre hassasiyetinde sağlamak için atom saatleri kullanır.",
    "Uzayda kırıntı bırakan yiyecekler yasaktır çünkü havada uçuşan kırıntılar astronotların gözüne kaçabilir.",
    "Kara delikler ömürlerinin sonunda Hawking radyasyonu yayarak yavaşça buharlaşabilirler.",
    "James Webb, mutlak sıfıra yakın bir sıcaklıkta çalışmak zorundadır ki kendi ısısı verileri bozmasın.",
    "Güneş Sistemi'ndeki en hızlı dönen gezegen Jüpiter'dir; bir gün sadece 10 saat sürer.",
    "Astronotlar Dünya'ya döndüklerinde 'ortostatik hipotansiyon' nedeniyle baygınlık geçirebilirler.",
    "Venüs'te yanardağların hala aktif olup olmadığı gökbilimciler arasında büyük bir tartışma konusudur.",
    "Gökbilimciler, 'yaşanabilir bölge' (Goldilocks) içindeki gezegenlerde sıvı su arayışına odaklanırlar.",
    "Evrenin genişleme hızı olan Hubble sabiti, farklı yöntemlerle ölçüldüğünde farklı sonuçlar veriyor.",
    "Yıldızların içindeki nükleer füzyon, demir atomuna ulaştığında yıldız için son yaklaşmış demektir.",
    "Mars'taki bir toz fırtınası, tüm gezegeni aylar boyunca karanlıkta bırakacak kadar büyüyebilir.",
    "Ay, Dünya etrafında dönerken her zaman aynı yüzünü bize gösteren 'kütle çekimsel kilitleme' altındadır.",
    "Jüpiter'in uydusu Io, sürekli gelgit bükülmeleri yaşadığı için içi her zaman sıcaktır.",
    "Uzayda yön tayini için kullanılan star-tracker kameraları, bilinen binlerce yıldızı tanıyacak şekilde kodlanmıştır.",
    "Kozmik ışınlar, uzaydaki astronotların katarakt olma riskini önemli ölçüde artırır.",
    "Süper kütleli kara delikler, galaksinin merkezindeki gazı yutarken muazzam parlaklıkta kuasarlar oluşturur.",
    "Evrenin sonu hakkında 'Büyük Sıçrama' teorisi, evrenin sürekli genişleyip daraldığını iddia eder.",
    "Bugün gökyüzü çok berrak, Satürn'ün halkalarını görmek için teleskobumu kuruyorum.",
    "Uzay araştırmaları, Dünya üzerindeki doğal kaynakları daha iyi yönetmemize yardımcı olan veriler sağlar.",
    "Güneş'in yüzeyindeki fışkırmalar (prominence), binlerce kilometre uzaya kadar yükselebilir.",
    "Uzayda saç kestirmek için saçları vakumlayan özel bir tıraş makinesi kullanılır.",
    "Bir sonraki ay tutulmasını izlemek için şimdiden en uygun gözlem noktasını belirledim."
]
tokenizer = Tokenizer()
tokenizer.fit_on_texts(space_texts)
total_words = len(tokenizer.word_index) + 1

input_sequence = []
for i in space_texts:
    token_list = tokenizer.texts_to_sequences([i])[0]
    for j in range(1, len(token_list)):
        n_gram_seq = token_list[:j + 1]
        input_sequence.append(n_gram_seq)

max_seq_len = max(len(i) for i in input_sequence)
input_sequence = pad_sequences(input_sequence, maxlen=max_seq_len)

X = input_sequence[:, :-1]
y = input_sequence[:, -1]
y = to_categorical(y, num_classes=total_words)

embedding_dim = 100
inputs = Input(shape=(max_seq_len - 1,))
embedding = Embedding(input_dim=total_words, output_dim=embedding_dim)(inputs)
lstm = LSTM(100, return_sequences=False)(embedding)
outputs = Dense(total_words, activation='softmax')(lstm)
model = Model(inputs=inputs, outputs=outputs)
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()
model.fit(X, y, epochs=100, batch_size=64, verbose=1)
test_loss, test_acc = model.evaluate(X, y)
print(f'test_loss: {test_loss:.3f}, test_acc: {test_acc:.3f}')

def text_generator(text, next_words):
    for _ in range(next_words):
        token_list = tokenizer.texts_to_sequences([text])[0]
        token_list = pad_sequences([token_list], maxlen=max_seq_len - 1)
        predict = model.predict(token_list, verbose=0)
        predict_word_index = np.argmax(predict, axis=-1)
        predict_word = tokenizer.index_word[predict_word_index[0]]
        text = text + ' ' + predict_word
    return text

text = 'Uzay kıyafetleri'
print(text_generator(text, 5))
# endregion